trigger:
- main

pool:
  vmImage: "ubuntu-latest"

variables:
- group: AccuKnox # Name of the variable group created in the Azure DevOps

- script: |
    pip install checkov
    checkov -d . --output json > checkov_report.json || true
    jq --arg repoLink "$(REPO_LINK)" --arg branch "$(Build.SourceBranchName)" \
      '. += [{"details": {"repo": $repoLink, "branch": $branch}}]' checkov_report.json > result.json
    cat result.json
    curl --location --request POST "https://cspm.demo.accuknox.com/api/v1/artifact/?tenant_id=$(TENANT_ID)&data_type=IAC&save_to_s3=true&label_id=$(LABEL)" \
      --header "Tenant-Id: $(TENANT_ID)" \
      --header "Authorization: Bearer $(ACCUKNOX_TOKEN)" \
      --form "file=@./result.json"
  displayName: 'IaC Scan'